spring.application.name=backend
server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}

samlego.app.googleClientId=${GOOGLE_CLIENT_ID:311664896204-ba5bigcf606thqcurl508ct91qmfbtbg.apps.googleusercontent.com}

spring.mail.host=${SMTP_HOST:}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.protocol=${SMTP_PROTOCOL:smtp}
spring.mail.properties.mail.smtp.auth=${SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMTP_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${SMTP_STARTTLS_REQUIRED:false}
spring.mail.properties.mail.smtp.ssl.enable=${SMTP_SSL_ENABLE:false}
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.socketFactory.port=${SMTP_PORT:587}
spring.mail.properties.mail.smtp.socketFactory.class=${SMTP_SOCKET_FACTORY_CLASS:}
spring.mail.properties.mail.smtp.socketFactory.fallback=false

samlego.mail.from=${SMTP_FROM:no-reply@samlego.com}
samlego.mail.admin=${ADMIN_EMAIL:}
samlego.resend.apiKey=${RESEND_API_KEY:}

telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.chat.id=${TELEGRAM_CHAT_ID:}
